# Generated by Django 6.0.5 on 2026-05-14 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tag',
            field=models.CharField(blank=True, choices=[('', 'None'), ('bestseller', 'Bestseller'), ('new', 'New Arrival')], default='', max_length=20),
        ),
    ]
